# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - dev
    - dev_qa
    - master
    - release/*

pool: 'Croem Build Servers'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  sonarQubeCon: 'SonarQube'
  buildConfiguration: 'Release'
  isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/dev')]

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core 7'
  inputs:
    version: 7.x
 
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: SonarQubePrepare@5
  displayName: 'Prepare analysis on SonarQube'
  enabled: true
  inputs:
    SonarQube: '$(sonarQubeCon)'
    scannerMode: 'MSBuild'
    projectKey: '$(System.TeamProject)_$(Build.DefinitionName)'
    projectName: '$(System.TeamProject)_$(Build.DefinitionName)'
    projectVersion: '$(Build.BuildNumber)'
    extraProperties: /d:sonar.cs.vscoveragexml.reportsPaths="**\*.coveragexml"
  continueOnError: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: build
    projects: '**/*.csproj'
 
- task: SonarQubeAnalyze@5
  enabled: true
  displayName: 'Run SonarQube Code Analysis'
  continueOnError: true

- task: SonarQubePublish@5
  enabled: true
  displayName: 'Publish Quality Gate Result'
  continueOnError: true
  inputs:
    pollingTimeoutSec: '300'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '--configuration release --output $(build.artifactstagingdirectory) /property:PublishWithAspNetCoreTargetManifest=false'
    zipAfterPublish: false
 
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    ArtifactName: myproject

- task: git-tag-on-release-task@9
  displayName: "Tag Artifact"